/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./src/assets/eye.glb
*/

import React, { useEffect, useState } from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { usePixeltoScene } from '../hooks/useThreeFunctions';

export default function Model(props) {
	const mesh = React.useRef();
	const [dir, setDir] = useState(0.0005);
	const { camera, size } = useThree();
	const maxSize = usePixeltoScene(window.innerWidth, window.innerHeight);
	const [color, setColor] = useState(new THREE.Color('hsl(256, 45%, 80%)'));
	const [pointer, setPointer] = useState({ x: 0, y: 0 });

	// window.addEventListener('mousemove', (e) => {
	// 	const ndcX = (e.pageX / size.width) * 2 - 1;
	// 	const ndcY = -(e.pageY / size.height) * 2 + 1;

	// 	// Create a 3D vector in NDC space
	// 	const vector = new THREE.Vector3(ndcX, ndcY, -90);

	// 	// Convert the vector from NDC space to world space
	// 	vector.unproject(camera);

	// 	setPointer(vector);
	// });

	const getSize = () => {
		const res = window.innerWidth / window.innerHeight;

		if (res <= 0.45) return maxSize.x * 0.09;
		if (res > 0.45 && res <= 0.6) return maxSize.x * 0.08;
		if (res > 0.6 && res <= 0.75) return maxSize.x * 0.075;
		if (res > 0.75 && res <= 1.02) return maxSize.x * 0.062;
		if (res > 1.2 && res <= 0.75) return maxSize.x * 0.075;
		if (res > 0.75 && res <= 1.25) return maxSize.x * 0.052;
		if (res > 1.25 && res <= 1.4) return maxSize.x * 0.045;
		if (res > 1.4 && res <= 1.6) return maxSize.x * 0.039;
		if (res > 1.6 && res <= 1.75) return maxSize.x * 0.038;
		if (res > 1.75) return maxSize.x * 0.039;

		return maxSize.x * 0.052;
	};

	const getPos = () => {
		const res = window.innerWidth / window.innerHeight;

		if (res <= 0.45) return [maxSize.x * 0.18, maxSize.y * 0.68, 0];
		if (res > 0.45 && res <= 0.6) return [maxSize.x * 0.23, maxSize.y * 0.67, 0];
		if (res > 0.6 && res <= 0.75) return [maxSize.x * 0.23, maxSize.y * 0.59, 0];
		if (res > 0.75 && res <= 1.02) return [maxSize.x * 0.35, maxSize.y * 0.55, 0];
		if (res > 1.02 && res <= 1.25) return [maxSize.x * 0.42, maxSize.y * 0.53, 0];
		if (res > 1.25 && res <= 1.6) return [maxSize.x * 0.6, maxSize.y * 0.5, 0];
		if (res > 1.6) return [maxSize.x * 0.6, maxSize.y * 0.5, 0];

		return [maxSize.x * 0.35, maxSize.y * 0.55, 0];
	};

	// useFrame(() => {
	// 	const worldPosition = new THREE.Vector3();
	// 	const x = (pointer.x * size.width) / (0.017778 * window.innerWidth);
	// 	const y = (pointer.y * size.height) / (0.0015 * window.innerHeight);
	// 	worldPosition.set(x, y, -90);
	// 	worldPosition.unproject(camera);

	// 	mesh.current.lookAt(worldPosition);
	// 	// console.log(mesh);
	// });

	const { nodes, materials } = useGLTF('/models/scene.glb');
	useEffect(() => {
		materials.purple.color = color;
		document.querySelector(':root').className !== 'dark'
			? setColor(new THREE.Color('hsl(256, 45%, 80%)'))
			: setColor(new THREE.Color('hsl(260, 12%, 32%)'));
	}, [color]);
	return (
		<group {...props} dispose={null}>
			<mesh
				ref={mesh}
				geometry={nodes?.eye.geometry}
				receiveShadow
				material={materials.purple}
				// position={[maxSize.x + 100, maxSize.y, 0]}
				position={getPos()}
				rotation={[0, 0, 0]}
				scale={getSize()}
			/>
		</group>
	);
}

useGLTF.preload('/models/scene.glb');
